---
name: TRD-WebRelayMail
version: 0.0.4
author:
  - 'Takuya Ichikawa <ichi@cpan.org>'
abstract: メールを送れないホストからのWebメールリレーモジュール
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI: 0
  Carp: 0
  LWP: 0
  Test::More: 0
  version: 0
provides:
  TRD::WebRelayMail:
    file: lib/TRD/WebRelayMail.pm
    version: 0.0.4
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
